### PR TITLE
Strip path off buffer files before calling get_id_number to avoid problem if path contains a dash

### PR DESCRIPTION
**Pull request by kellymclaughlin**
I ran across this problem while quickchecking `riak_kv_index_backend`. I set the data_root to `test/merge_index-backend` and it exposed the problem.

### CODE REVIEW

**Comment by rzezeski** [comment]
This should also address [this issue](https://issues.basho.com/show_bug.cgi?id=861).

**Comment by rzezeski** [comment]
It also address issue [1086](https://issues.basho.com/show_bug.cgi?id=1086).

**Comment by Vagabond** [comment]
I've tested this and the patch does fix the issue. However, why didn't you use filename:basename or something instead of that substr. Also, a unit test would be nice (not sure how feasible it is, though).

**Comment by Vagabond** [comment]
+1 for merge

**Pull request closed without merging**
