### PR TITLE
Az344 resurrect qc tests

### PR DESCRIPTION
**Pull request by rzezeski**
A bunch of commits to reinstate/fix the old QC tests.  I also added some tests to get a bit more coverage and made a very small tweak to `mi_segment:possibly_add_iterator/2` to build a list, not a nested list.  Oh, and I added -specs and edoc annotations to the API.

I'd really like some feedback on my QC tests since it's my first time using it.

### CODE REVIEW

**Comment by slfritchie** [comment]
wrt the re-indenting patch, take it or leave it.  I don't like > 80 char lines in code,
and indenting ?LET and other QuickCheck macros the same way that Erlang code
is usual indented gets shifted very right very quickly.  Besides, John Hughes
doesn't indent his ?LET macros the usual way.  :-)

**Comment by slfritchie** [comment]
I've a few more comments:
- Move the function definitions in common.hrl to common.erl
- In mi_buffer_tests, currently a single mi_buffer:write/2 is used.  If you
  change generator to a list of list of entries, then call
  mi_buffer:write/2 several times, you'll also test that mi_buffer's iterator
  correctly handles multiple writes within the same buffer.  Then verify that iterator gets
  all entries in the correct order.
  *\* Ditto for Entries generators in mi_segment_tests.erl
- Does a nearly-duplicate request to edit `equals(lists:sort(L1), lists:sort(L2))` to be
  `equals(L1, lists:reverse(L2))` also make sense for mi_segments_tests.erl?

**Comment by rzezeski** [comment]
1. Done
2. Re calling mi_buffer:write/2 multiple times in test--I agree and now that I've studied up on QuickCheck some I'll do one better and say I should have used statem to test mi_buffer and mi_segment b/c then I could test a random sequence of calls rather than just random data with the same series of calls each time (although maybe both have their place).  I'll be adding some more tests to test merge_index at the API level using statem which should get more sophisticated coverage.
3. No b/c mi_segment sorts the data.

**Comment by slfritchie** [comment]
Thanks for the edits, looks good to merge, thanks.

**Pull request merged**
